override PVRSRV_DIR := services
override HOST_PRIMARY_ARCH := host_x86_64
override TARGET_PRIMARY_ARCH := target_riscv64
override TARGET_SECONDARY_ARCH :=
override TARGET_ALL_ARCH := target_riscv64
override TARGET_FORCE_32BIT :=
override PVR_ARCH := rogue
override METAG_VERSION_NEEDED := 2.8.1.0.3
override MIPS_VERSION_NEEDED := 2014.07-1
override RISCV_VERSION_NEEDED := 2024.1.0
override KERNELDIR := /home/icenowy/builds/linux/th1520
override KERNEL_ID := 6.6.113-th1520+
override PVRSRV_MODULE_BASEDIR := /lib/modules/6.6.113-th1520+/extra/
override KERNEL_COMPONENTS := srvkm drm_nulldisp
override KERNEL_CROSS_COMPILE := /opt/abcross/riscv64/bin/riscv64-aosc-linux-gnu-
override WINDOW_SYSTEM := wayland
override PVRSRV_MODNAME := pvrsrvkm
override PVR_BUILD_DIR := xuantie_linux
override PVR_BUILD_TYPE := release
override SUPPORT_RGX := 1
override DISPLAY_CONTROLLER := drm_nulldisp
override PVR_SYSTEM := rgx_xuantie
override PVR_LOADER :=
override BUILD := release
override SORT_BRIDGE_STRUCTS := 1
override DEBUGLINK := 1
override RGX_BNC := 36.V.104.182
override PVRSRV_ENABLE_XD_MEM := 1
override PVRSRV_TRACE_ROGUE_EVENTS := 1
override SUPPORT_PHYSMEM_TEST := 1
override SUPPORT_MIPS_64K_PAGE_SIZE :=
override RGX_NUM_DRIVERS_SUPPORTED := 1
override RGX_FW_HEAP_OSID_ASSIGNMENT := RGX_FW_HEAP_USES_FIRMWARE_OSID
override VMM_TYPE := stub
override SUPPORT_POWMON_COMPONENT := 1
override RGX_SECONDARY_OS_CLOCK_SOURCE := sched
override PDVFS_COM_HOST := 1
override PDVFS_COM_AP := 2
override PDVFS_COM_PMC := 3
override PDVFS_COM_IMG_CLKDIV := 4
override PDVFS_COM_SYSREG := 5
override PDVFS_COM := PDVFS_COM_HOST
override SUPPORT_FW_CORE_CLK_RATE_CHANGE_NOTIFY := 1
override SUPPORT_PVR_GPIO := 1
override PVR_HANDLE_BACKEND := idr
override SUPPORT_DMABUF_BRIDGE := 1
override SUPPORT_USC_BREAKPOINT := 1
override SUPPORT_DI_APPHINT_IMPL := 1
override SUPPORT_WRAP_EXTMEM := 1
override SUPPORT_NATIVE_FENCE_SYNC := 1
override SUPPORT_BUFFER_SYNC := 1
